import pytest

from vnstock_bot.export import TEMPLATES, PineParams, generate, write_to_file


def test_all_templates_generate_valid_pine():
    for tpl in TEMPLATES:
        code = generate(tpl)
        assert code.startswith("// Generated by vnstock-bot")
        # Must contain the //@version=6 pragma somewhere
        assert "//@version=6" in code
        # indicator or strategy declaration
        assert ("strategy(" in code or "indicator(" in code)


def test_breakout_template_contains_expected_knobs():
    code = generate("breakout", PineParams(
        lookback=55, vol_mult=2.5, stop_pct=0.07, target_pct=0.20,
        strategy_name="My Breakout",
    ))
    assert "\"Donchian lookback\"" in code
    assert "55" in code
    assert "2.5" in code
    assert "0.07" in code
    assert "My Breakout" in code


def test_ichimoku_template_has_cloud():
    code = generate("ichimoku")
    assert "tenkan" in code.lower()
    assert "kijun" in code.lower()
    assert "span_a" in code and "span_b" in code


def test_unknown_template_raises():
    with pytest.raises(ValueError, match="unknown template"):
        generate("not-a-template")  # type: ignore[arg-type]


def test_write_to_file_creates_pine_file(tmp_path):
    path = write_to_file("breakout", out_dir=tmp_path, filename="test_breakout")
    assert path.is_file()
    assert path.suffix == ".pine"
    content = path.read_text(encoding="utf-8")
    assert "//@version=6" in content


def test_commission_applied_in_template():
    code = generate("breakout", PineParams(commission_pct=0.3))
    assert "0.3" in code
