"""Pine Script v6 generator (PLAN_V2 §7, skills/tool/pine-script.md).

5 templates match the core strategy skills:
  - breakout (Donchian N-day + volume multiplier)
  - ma_cross (fast/slow SMA cross)
  - rsi_mr (RSI mean-reversion + trend filter)
  - ichimoku (cloud + cross + Kijun exit)
  - mf_screen (multi-factor indicator, not a strategy)

No external dep — pure string templating. Output is valid Pine v6 that
pastes directly into TradingView Pine Editor.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from vnstock_bot.data.holidays import now_vn

TemplateName = Literal[
    "breakout", "ma_cross", "rsi_mr", "ichimoku", "mf_screen",
]
TEMPLATES: tuple[TemplateName, ...] = (
    "breakout", "ma_cross", "rsi_mr", "ichimoku", "mf_screen",
)


@dataclass
class PineParams:
    strategy_name: str = "vnstock-bot strategy"
    # breakout
    lookback: int = 20
    vol_mult: float = 2.0
    stop_pct: float = 0.08               # -8% hard stop
    target_pct: float = 0.15             # +15% target
    # ma_cross
    ma_fast: int = 20
    ma_slow: int = 50
    # rsi_mr
    rsi_length: int = 14
    rsi_oversold: int = 30
    rsi_overbought: int = 70
    trend_ma: int = 50
    # ichimoku (9/26/52 standard)
    tenkan: int = 9
    kijun: int = 26
    senkou_b: int = 52
    # mf_screen
    momentum_min: float = 0.05           # 5% over 20d
    rsi_min: int = 55
    rsi_max: int = 75
    vol_surge: float = 1.5
    # common
    initial_capital: int = 100_000_000
    commission_pct: float = 0.25         # round-trip VN
    source_skill: str | None = None
    extra_comment: str = ""

    metadata: dict[str, object] = field(default_factory=dict)


# ---------------------------------------------------------------- header

def _header(template: TemplateName, params: PineParams) -> str:
    today = now_vn().strftime("%Y-%m-%d")
    src = params.source_skill or "—"
    extra = f"// {params.extra_comment}\n" if params.extra_comment else ""
    return (
        f"// Generated by vnstock-bot {today}\n"
        f"// Template: {template}\n"
        f"// Strategy: {params.strategy_name}\n"
        f"// Source skill: {src}\n"
        f"{extra}"
        f"// Paste vào TradingView Pine Editor → 'Add to Chart'.\n"
    )


# ---------------------------------------------------------------- templates

def _tpl_breakout(p: PineParams) -> str:
    return f"""//@version=6
strategy("{p.strategy_name}", overlay=true,
         initial_capital={p.initial_capital},
         commission_type=strategy.commission.percent,
         commission_value={p.commission_pct})

length   = input.int({p.lookback}, "Donchian lookback")
vol_mult = input.float({p.vol_mult}, "Volume multiplier")
stop_pct = input.float({p.stop_pct}, "Hard stop %", step=0.01)
tgt_pct  = input.float({p.target_pct}, "Take-profit %", step=0.01)

hh      = ta.highest(high, length)[1]
vol_ma  = ta.sma(volume, length)
entry   = close > hh and volume >= vol_ma * vol_mult

if entry
    strategy.entry("Long", strategy.long)
    strategy.exit("Exit", from_entry="Long",
                  stop=close * (1 - stop_pct),
                  limit=close * (1 + tgt_pct))
"""


def _tpl_ma_cross(p: PineParams) -> str:
    return f"""//@version=6
strategy("{p.strategy_name}", overlay=true,
         initial_capital={p.initial_capital},
         commission_type=strategy.commission.percent,
         commission_value={p.commission_pct})

fast = ta.sma(close, input.int({p.ma_fast}, "Fast MA"))
slow = ta.sma(close, input.int({p.ma_slow}, "Slow MA"))

long_cond = ta.crossover(fast, slow)
exit_cond = ta.crossunder(fast, slow)

if long_cond
    strategy.entry("Long", strategy.long)
if exit_cond
    strategy.close("Long")

plot(fast, color=color.blue)
plot(slow, color=color.orange)
"""


def _tpl_rsi_mr(p: PineParams) -> str:
    return f"""//@version=6
strategy("{p.strategy_name}", overlay=false,
         initial_capital={p.initial_capital},
         commission_type=strategy.commission.percent,
         commission_value={p.commission_pct})

rsi_len    = input.int({p.rsi_length}, "RSI length")
oversold   = input.int({p.rsi_oversold}, "Oversold")
overbought = input.int({p.rsi_overbought}, "Overbought")
trend_ma   = ta.sma(close, input.int({p.trend_ma}, "Trend MA"))

rsi_v = ta.rsi(close, rsi_len)

// Mean-reversion + trend filter: only long when above long-term MA
long_cond = rsi_v <= oversold and close > trend_ma
exit_cond = rsi_v >= overbought

if long_cond
    strategy.entry("Long", strategy.long)
if exit_cond
    strategy.close("Long")

plot(rsi_v)
hline(oversold, "OS", color=color.green)
hline(overbought, "OB", color=color.red)
"""


def _tpl_ichimoku(p: PineParams) -> str:
    return f"""//@version=6
strategy("{p.strategy_name}", overlay=true,
         initial_capital={p.initial_capital},
         commission_type=strategy.commission.percent,
         commission_value={p.commission_pct})

tenkan_len  = input.int({p.tenkan}, "Tenkan")
kijun_len   = input.int({p.kijun}, "Kijun")
senkou_b_len = input.int({p.senkou_b}, "Senkou B")

tenkan  = (ta.highest(high, tenkan_len) + ta.lowest(low, tenkan_len)) / 2
kijun   = (ta.highest(high, kijun_len)  + ta.lowest(low, kijun_len))  / 2
span_a  = (tenkan + kijun) / 2
span_b  = (ta.highest(high, senkou_b_len) + ta.lowest(low, senkou_b_len)) / 2

above_cloud  = close > span_a and close > span_b
golden_cross = ta.crossover(tenkan, kijun)

if golden_cross and above_cloud
    strategy.entry("Long", strategy.long)
if close < kijun
    strategy.close("Long")

plot(tenkan, color=color.blue)
plot(kijun, color=color.red)
p1 = plot(span_a, color=color.green)
p2 = plot(span_b, color=color.orange)
fill(p1, p2, color=(span_a > span_b ? color.new(color.green, 80) : color.new(color.red, 80)))
"""


def _tpl_mf_screen(p: PineParams) -> str:
    return f"""//@version=6
// Multi-factor screen (indicator, not a strategy — Pine can't do
// cross-section ranking natively).
indicator("{p.strategy_name}", overlay=false)

mom_min   = input.float({p.momentum_min}, "Momentum 20d min")
rsi_min   = input.int({p.rsi_min}, "RSI min")
rsi_max   = input.int({p.rsi_max}, "RSI max")
vol_surge = input.float({p.vol_surge}, "Volume surge multiplier")

momentum_20 = close / close[20] - 1
rsi_14      = ta.rsi(close, 14)
vol_ok      = volume > ta.sma(volume, 20) * vol_surge

meets = momentum_20 > mom_min and rsi_14 > rsi_min and rsi_14 < rsi_max and vol_ok

plotshape(meets, title="Signal", style=shape.triangleup,
          location=location.belowbar, color=color.green, size=size.small)
plot(momentum_20 * 100, title="Momentum 20d %")
"""


_DISPATCH: dict[TemplateName, Callable[[PineParams], str]] = {
    "breakout":  _tpl_breakout,
    "ma_cross":  _tpl_ma_cross,
    "rsi_mr":    _tpl_rsi_mr,
    "ichimoku":  _tpl_ichimoku,
    "mf_screen": _tpl_mf_screen,
}


def generate(template: TemplateName, params: PineParams | None = None) -> str:
    if template not in _DISPATCH:
        raise ValueError(
            f"unknown template {template!r}; available: {list(_DISPATCH)}"
        )
    p = params or PineParams()
    return _header(template, p) + "\n" + _DISPATCH[template](p)


def write_to_file(
    template: TemplateName,
    params: PineParams | None = None,
    out_dir: Path | str | None = None,
    filename: str | None = None,
) -> Path:
    from vnstock_bot.config import get_settings
    out_dir = Path(out_dir) if out_dir else (
        get_settings().absolute_raw_dir.parent / "export" / "pine"
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    p = params or PineParams()
    stem = filename or f"{template}_{now_vn().strftime('%Y%m%d_%H%M%S')}"
    path = out_dir / f"{stem}.pine"
    path.write_text(generate(template, p), encoding="utf-8")
    return path
